namespace Age.Platforms.Linux.LibDecor;

internal enum libdecor_window_state
{
	LIBDECOR_WINDOW_STATE_NONE         = 0,
	LIBDECOR_WINDOW_STATE_ACTIVE       = 1 << 0,
	LIBDECOR_WINDOW_STATE_MAXIMIZED    = 1 << 1,
	LIBDECOR_WINDOW_STATE_FULLSCREEN   = 1 << 2,
	LIBDECOR_WINDOW_STATE_TILED_LEFT   = 1 << 3,
	LIBDECOR_WINDOW_STATE_TILED_RIGHT  = 1 << 4,
	LIBDECOR_WINDOW_STATE_TILED_TOP    = 1 << 5,
	LIBDECOR_WINDOW_STATE_TILED_BOTTOM = 1 << 6,
	LIBDECOR_WINDOW_STATE_SUSPENDED    = 1 << 7,
};
