<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Age.Core/Age.Core.csproj" />
    <ProjectReference Include="../Age.Numerics/Age.Numerics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Condition="$(IsWindows)" Include="../Age.Platforms.Windows/Age.Platforms.Windows.csproj"></ProjectReference>
    <ProjectReference Condition="$(IsLinux)"   Include="../Age.Platforms.Linux/Age.Platforms.Linux.csproj"></ProjectReference>
  </ItemGroup>

</Project>
